using './main.bicep'

param projectName = ''
param AppResourceGroup = ''
param DataResourceGroup = ''
param MonitoringResourceGroup = ''
param regionAbbreviation = ''
param sku = ''
param osType = ''
param RuntimeStack = ''
param RuntimeVersion = ''
param vNetName = ''
param vNetRG = ''
param peSubnetName = ''
param vNetAddressSpace = ''
param subnetAddressSpace = ''
param subnetDescription = ''
param Owner = ''
param CostCenter = ''
param subscriptionId = ''

